import './globals.css'
import type { Metadata } from 'next'
import { Inter , Urbanist } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { Navbar } from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })
const urbanist = Urbanist({ subsets: ['latin'] ,weight:['100','200',"500","900","800"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={urbanist.className}>
       
        {children}</body>
    </html>
    </ClerkProvider>
  )
}
